language: node_js
node_js:
- '4.3'
env:
- TEST_DIR=compute/lambda/functions/sample-lambda
script: cd $TEST_DIR && npm install && npm test
deploy:
  provider: lambda
  function_name: sample-lambda
  role: arn:aws:iam::583763756569:role/lambda_basic_execution
  handler_name: index.handler
  access_key_id: AKIAJDCW7VJVH6ITDFAQ
  secret_access_key:
    secure: I9yXCfXqtSKAT0vLigkpi8qhvwQk0OjneToEAUX2Q73Koj/OUeHemkAdaQMlNvYNchCZDbtuA+W+avytBhPTBX0Dkko479fnAZmjzWbmNWe+84L+ogH6g4qlBrToslYxT8TMhJB1jO16BdKzIl4CMUNEfiVTtWFMHnNQ0/teBZuFAS0zjpThPNNTbdzVqmQnCOFGOhNNVrhZM9p0pJyuToVtq0v79RQWtKTV7b6wFVbZ50+35Qc4cyKiN0gwlLmMvkRL1VUyQFKKh20rx1Z6uhpuLePOTncDNkREkBTxyLcvKv2CGJim1OhWawLxtVpY3uSnlqU1DzemB1w857c3GhbwA0ff59IP/gWgBIW0nZaOSg9ghEiASNwlwD1tKbJ2uLoICpYk41xYV03BX8t8kaUCrvf3004vStvYijEJyyGjatl3CusnwbmQudnEqWKm2SHpe1uLOP/VN0d6CqBjTNFJbeWeCsxp/doWQwXAGh07XMjlnSS5OfIVGEGqy7XJiiKrCumEryHCH1Bu72jeFkjA6lAloViUpZ34OZODVqf4yLMPWte+v8mphiZNxKRKLVGT869HgGQw4Z+hQHNzHjihhUnD2FLdeAY+R8EOCfJEviiyeByrFdRxCvl4cek78MVQDfwc8Rcpo6vdz11IQeajhznAn0LfbIEJ7PX+lTw=
